[package]
name = "ppoprf"
version = "0.0.1"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", default-features = false }
rand_core = { version = "0.6.3", features = [ "getrandom" ] }
rand_core_ristretto = { version="0.5.1", package="rand_core" }
bitvec = "1.0.1"
curve25519-dalek =  { version = "3.2.0", features = [ "serde" ] }
serde = "1.0.140"
strobe-rs = "0.7.1"
strobe-rng = { path = "../strobe-rng" }
base64 = "0.13"
bincode = "1.3.3"
derive_more = "0.99"
zeroize = { version = "1.5.7", features = [ "derive" ] }

[dev-dependencies]
actix-web = "4.1.0"
base64 = "0.13.0"
criterion = "0.3.6"
env_logger = "0.9.0"
log = "0.4.17"
reqwest = { version = "0.11.11", features = [ "blocking", "json" ] }
dotenv = "0.15"
insta = "1.17.1"
matches = "0.1.9"

[[bench]]
name = "bench"
harness = false
