[package]
name = "ppoprf"
version = "0.0.1"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4", default-features = false }
rand_core = { version = "0.6.3", features = [ "getrandom" ] }
rand_core_ristretto = { version="0.5.1", package="rand_core" }
bitvec = "0.22.3"
curve25519-dalek =  { version = "3.2.0", features = [ "serde" ] }
criterion = "0.3.5"
serde = "1.0.136"
strobe-rs = "0.7.1"
strobe-rng = { path = "../strobe-rng" }
base64 = "0.13"
derive_more = "0.99"
zeroize = { version = "1.5.4", features = [ "derive" ] }

[dev-dependencies]
actix-web = "4.0.1"
base64 = "0.13.0"
env_logger = "0.9.0"
log = "0.4.17"
reqwest = { version = "0.11.10", features = [ "blocking", "json" ] }
dotenv = "0.15"

[[bench]]
name = "bench"
harness = false
